### ISSUE TITLE
impossible to get rid of added layers in particular stream

### ISSUE THREAD

**Issue by winter3angle** [little-dude/simple-ostinato#14]
Hi, pal.
Looks like it is impossible to get rid of some added layers using code like this
``` python
stream.layers.append(proto_layer)
stream.save()
del stream.layers[:]
stream.save()
```
Because looks like you're fetching layers while saving stream thus preventing them from being deleted. Am I missing something or there are actually issue persists?

**Comment by little-dude** [comment]
That seems to work for me. Does this work for you?

```python
stream.layers.append(proto_layer)
stream.save()
stream.layers = []
stream.save()
```
